spring:
  thymeleaf:
    prefix: classpath:/templates/
#    开发环境为false
    cache: false
  devtools:
    restart:
#    设置热部署的路径
      additional-exclude: /templates/**,src/main/java
#      配置数据源
  datasource:
    url: jdbc:mysql://47.94.251.74:3805/oke?useUnicode=true&amp;characterEncoding=UTF-8&amp;tinyInt1isBit=false
    username: root
    password: 5zqvur6k
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  typeAliasesPackage: com.example.demo.entity
  mapperLocations: classpath:mapper/*.xml
